// <auto-generated />
using System;
using GoVote.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GoVote.Migrations.VotingTypeDatabase
{
    [DbContext(typeof(VotingTypeDatabaseContext))]
    [Migration("20200109174201_VotingTypeDb")]
    partial class VotingTypeDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GoVote.Data.VotingType", b =>
                {
                    b.Property<Guid>("VotingTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("VotingTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VotingTypeID");

                    b.ToTable("VotingTypes");

                    b.HasData(
                        new
                        {
                            VotingTypeID = new Guid("8254d087-4ad7-4069-816f-5ed97d119716"),
                            VotingTypeName = "Alegeri prezidentiale"
                        },
                        new
                        {
                            VotingTypeID = new Guid("ae040cc6-c820-4f54-8173-0510907c04ee"),
                            VotingTypeName = "Alegeri parlamentare"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
