// <auto-generated />
using System;
using GoVote.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GoVote.Migrations.LoginTokenDatabase
{
    [DbContext(typeof(LoginTokenDatabaseContext))]
    partial class LoginTokenDatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GoVote.Data.LoginToken", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CitizenID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("ExpiresAfter")
                        .HasColumnType("time");

                    b.HasKey("ID");

                    b.ToTable("LoginTokens");

                    b.HasData(
                        new
                        {
                            ID = new Guid("68e0883b-cbd7-4338-b0d6-b513a57cf53b"),
                            CitizenID = new Guid("79923d83-a092-443b-8120-6e8466925abc"),
                            CreationDate = new DateTime(2020, 1, 6, 16, 31, 36, 676, DateTimeKind.Local).AddTicks(8641),
                            ExpiresAfter = new TimeSpan(0, 1, 0, 0, 0)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
